### ISSUE TITLE
Program updating it's name / Windows Defender going crazy

### ISSUE THREAD

**Issue by hotspicytaco** [KebsCS/KBotExt#105]
Is this intended behaviour? The file name was originally KBot.exe

![image](https://user-images.githubusercontent.com/3945842/220478960-9407255b-0e51-4383-a9d4-5d9be0fe6aee.png)

![image](https://user-images.githubusercontent.com/3945842/220479120-a201f727-176a-4cdc-a83e-0d5cd32d78c6.png)

![image](https://user-images.githubusercontent.com/3945842/220479248-0fed3a51-7f1a-4823-b7c6-38fce3692aca.png)

It won't open the league client with hook now.

**Comment by KebsCS** [comment]
Yes, the program changing its name is intended when you enable "Auto-rename"
![image](https://user-images.githubusercontent.com/22469895/220480149-50510da4-18e7-4a2c-8eef-9509776a575b.png)

And league not launching when IFEO is hooked and auto-rename is enabled is also a known bug 
![image](https://user-images.githubusercontent.com/22469895/220480308-2c8443dc-b45e-431f-961e-e73737e0cd01.png)

**Comment by KebsCS** [comment]
Added in https://github.com/KebsCS/KBotExt/commit/b35acc6ce3f0cd01f3747b356d75595a21364245
