### ISSUE TITLE
Is it possible to unlock "Chibi Icons"?

### ISSUE THREAD

**Issue by Espnandro** [KebsCS/KBotExt#106]
In the League Profile Tool it used to be possible to equip a group of "Chibi Icons" but the project is dead and icons now show blank when equipped.  
![image](https://user-images.githubusercontent.com/123902154/220931971-2b567fb3-2b88-4587-98c9-899e91371034.png)

**Comment by Espnandro** [comment]
Also, are any icons other than the ones you own usable with this tool? Similar to how any profile background can be used.

**Comment by KebsCS** [comment]
The chibi icons got removed. You can set any icon with "Submit 2" button in the Profile tab, but it'll only be seen in the friendlist.(Also for your friends). All icons ids are here: https://raw.communitydragon.org/latest/game/assets/ux/summonericons/

**Comment by Espnandro** [comment]
> 

I see, does submit 2 reset every time I close the client in the same way chat rank resets? Also, does this mean no icons can be equipped to profile aside from the ones owned by the account? To avoid opening another thread on a side note I'd like to ask what "launch legacy client" does. I appreciate the communication the tool seems to combine what I previously used multiple separate programs for.

**Comment by KebsCS** [comment]
> > 
> 
> I see, does "submit 2" reset every time I close the client in the same way chat rank resets? Also, does this mean no icons can be equipped to profile aside from the ones owned by the account? To avoid opening another thread on a side note I'd like to ask what "launch legacy client" does. I appreciate the communication the tool seems to combine what I previously used multiple separate programs for.

Correct, and legacy client got fixed, but rn I use it to test stuff without logging in
