### ISSUE TITLE
Buying champs in champselect

### ISSUE THREAD

**Issue by Chadists** [KebsCS/KBotExt#108]
Since you can refund any champion, it would be nice that you could buy any champ when you see the draft, and refund it after the game.
Thanks for your work !

**Comment by BennyExtreme** [comment]
From what I've seen champions bought after the start of champ select phase do not appear in game and are not selectable even through the api...

@KebsCS is that right?

PS: Some time ago I created a private tool that was supposed to work that way, but I couldn't get it to work...
![Screenshot 1](https://user-images.githubusercontent.com/75805898/222216484-2156cd03-fc99-44f6-86af-6162e5d06c2d.png)
![Screenshot 2](https://user-images.githubusercontent.com/75805898/222216262-93eee525-dff1-4284-8dc3-a99ece6ab4a8.png)

**Comment by KebsCS** [comment]
@Chadists it was planned but I don't have time to add it rn, thanks for the suggestion

@BennyExtreme there is a rtmp call that refreshes owned champions, it works in champ select too

**Comment by BennyExtreme** [comment]
> @BennyExtreme there is a rtmp call that refreshes owned champions, it works in champ select too

Good to hear that, however it's still outside the http API so you have to touch other stuff to make it work.

**Comment by KebsCS** [comment]
> > @BennyExtreme there is a rtmp call that refreshes owned champions, it works in champ select too
> 
> Good to hear that, however it's still outside the http API so you have to touch other stuff to make it work.

You can call rtmp with the invoke tab, but I've just checked the same endpoint as before and it seems to only work in custom games, unless I've missed smth

**Comment by KebsCS** [comment]
Looks like it's not possible outside of custom games. The champion list is initialized only upon joining with indicateAfkReadiness ledge call. I don't know of any bypass for it
