### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by vemboy** [KebsCS/KBotExt#111]
Dodge function should have timer so it dodges last milisecond so you can avoid dodging if one of your other teammates is going to dodge

**Comment by ReprimandedKaito** [comment]
This suggestion has been brought up a few times before (as in #39 and #66).
There should be an FAQ entry or a **Non-goals** section about it.

> Last second dodge is unfortunately impossible, because the client doesn't share the exact timer and the time can vary a lot depending on server and connection speed
>
> -- https://github.com/KebsCS/KBotExt/issues/66#issuecomment-1382323433
