### ISSUE TITLE
how to start game without accepting the RiotClient terms?

### ISSUE THREAD

**Issue by dd395674558** [KebsCS/KBotExt#117]
How to start game without accepting the RiotClient terms?it seems like doesn't work now.And where to find all the Lcu api endpoints?

**Comment by dd395674558** [comment]
Sorry sir I think I just asked a wrong question.I mean , how to accept the RiotClient terms by using Lcu Api?

**Comment by dd395674558** [comment]
Sorry sir I think I just asked a wrong question.I mean , how to accept the RiotClient terms by using Lcu Api?
&nbsp;


临时公
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月13日(星期四) 晚上10:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [KebsCS/KBotExt] how to start game without accepting the RiotClient terms? (Issue #117)





 
hello,
 I have already try, but the thing is your status doesn't allow you to play till you didn't accept ... if somone find how to bypass please send :D

**Comment by NoeMoyen** [comment]
create a new account, open the dev tool, and check the request you make when you click on the accept therm button

**Comment by KebsCS** [comment]
> How to start game without accepting the RiotClient terms?it seems like doesn't work now.And where to find all the Lcu api endpoints?

https://lcu.kebs.dev/ or https://riotclient.kebs.dev/
or you can enable debugger IFEO in the app and capture the request you want with Fiddler
