### ISSUE TITLE
Improvement for invite

### ISSUE THREAD

**Issue by megastorm7** [KebsCS/KBotExt#118]
It would be nice if we could have a button to invite all friends from --> drop down menu ( folder ). 
Same behavior as Remove all friends but for invite
![image](https://user-images.githubusercontent.com/16835494/232098590-302d589e-d1e6-4c74-bc89-0b8368ea51e9.png)

**Comment by KebsCS** [comment]
Thanks, added in https://github.com/KebsCS/KBotExt/commit/e533dbba4fdf2dc1144f365265790030289be183
Can be already downloaded at: https://github.com/KebsCS/KBotExt/releases/tag/prerelease
