### ISSUE TITLE
When I use it on PBE server (Ver.13.8), I got this error message

### ISSUE THREAD

**Issue by xsshk** [KebsCS/KBotExt#119]
This is the content of the popup
![image](https://user-images.githubusercontent.com/71780423/232210563-7246de54-3914-434a-803e-abb0f4295a45.png)

In addition, I found that when the Register debugger IFEO function is enabled, Legacy Clinet cannot be started normally.
I think it might have something to do with this

**Comment by KebsCS** [comment]
Thanks for the report, fixed in https://github.com/KebsCS/KBotExt/commit/04ec41a95524c60448485bf10bee037598885671

Also Legacy Client is not supported, since it's partially patched, and the debugger wouldn't be able to capture anything
