### ISSUE TITLE
search bar (combo box) is empty

### ISSUE THREAD

**Issue by nc-gp** [KebsCS/KBotExt#124]
i don't know what happend, but probably after restart should be back to normal.
also i think (atleast in my pc) the "combo box" is way too high?
imo transparency of combo background should be set to 0

edit: i have just checked the combo after restart (multiple times), and either way one of them are empty

![KBotExt_3MblhaYgcQ](https://user-images.githubusercontent.com/34553547/233420725-defe59ca-ddc5-4657-b718-c27567ecc067.png)
![KBotExt_1hDwsyfsM9](https://user-images.githubusercontent.com/34553547/233420729-22b5ffe5-0b8d-4fbf-83e5-8e73207d75db.png)

**Comment by MavYT29** [comment]
does the free aram boost work on all accounts or do you need 20rp to work?

**Comment by nopressure777** [comment]
@KebsCS Is this happening for u also or is it just us?

**Comment by KebsCS** [comment]
> @KebsCS Is this happening for u also or is it just us?

Doesn't happen to me, sometimes one combobox is empty but after switching tabs it fixes itself

**Comment by bit-paper** [comment]
> Doesn't happen to me, sometimes one combobox is empty but after switching tabs it fixes itself

You're right, just checked and after switching tabs it fixes.

**Comment by nopressure777** [comment]
> > Doesn't happen to me, sometimes one combobox is empty but after switching tabs it fixes itself
> 
> You're right, just checked and after switching tabs it fixes.

What do you mean switch tab? Like Game tab into Profile tab?

**Comment by Kokman12331** [comment]
You can also restart the UX in the "misc" tab :D That also works for me
