### ISSUE TITLE
Free aram boost why doesn't it work?

### ISSUE THREAD

**Issue by MavYT29** [KebsCS/KBotExt#126]
I spent 200rp why the free aram boost still not working how to enable it and what to do to make it work?

**Comment by KebsCS** [comment]
You dont need to spend any rp, it buys the champion by itself. It's all explained when you hover over the question mark

**Comment by MavYT29** [comment]
> You dont need to spend any rp, it buys the champion by itself. It's all explained when you hover over the question mark

why does it say Boost is not available for this account

**Comment by Dorlander** [comment]
> > You dont need to spend any rp, it buys the champion by itself. It's all explained when you hover over the question mark
> 
> why does it say Boost is not available for this account

u need around 1k rp XD

**Comment by KebsCS** [comment]
> > > You dont need to spend any rp, it buys the champion by itself. It's all explained when you hover over the question mark
> > 
> > 
> > why does it say Boost is not available for this account
> 
> u need around 1k rp XD

Depends on the account, it buys a champion if your rp minus champ price is less than 95
