### ISSUE TITLE
Missing install cpr

### ISSUE THREAD

**Issue by hoyen204** [KebsCS/KBotExt#130]
I'm sorry my english is bad.
In this instruct https://github.com/KebsCS/KBotExt#development is missing install cpr for build.

**Comment by hoyen204** [comment]
Commands used to install cpr:

vcpkg install cpr:x64-windows-static
vcpkg install cpr:x86-windows-static

**Comment by frank824** [comment]
having same issue

**Comment by KebsCS** [comment]
> having same issue

Just run the commands from the reply above, it isn't added to the readme yet since it's a pre-release
