### ISSUE TITLE
How to use free boost？

### ISSUE THREAD

**Issue by zwy923** [KebsCS/KBotExt#132]
What is the correct operation process? The following operation process is feasible, but it will consume RP.

I have around 400 RPs in my account. After clicking on Free ARAM boost, I started a game (the last game was a day ago). After playing about five games, I clicked on 'refund RP' and the RP was returned. However, the RP was consumed the next time I launched the game.

Can someone tell me the correct operating procedure?

**Comment by KebsCS** [comment]
![image](https://user-images.githubusercontent.com/22469895/236689971-3397a8c6-5fc2-4e0f-8119-7bf7a0a07c4b.png)

**Comment by zwy923** [comment]
> ![image](https://user-images.githubusercontent.com/22469895/236689971-3397a8c6-5fc2-4e0f-8119-7bf7a0a07c4b.png)

yes, I can see that, but I still have some confusion, such as "you have to wait at least 1 hour", which means that I need to click on Free boost one hour after the last game, or do I need to click on Free boost and then after completing the last game, wait for one hour and then clicking on Refund RP.
Perhaps my question is silly, but what I want to understand is what button to click on at what time, so that my RP is not consumed.

**Comment by KebsCS** [comment]
Refund at least 1h after last game

**Comment by zwy923** [comment]
ok, got it. Thx for your work!
