### ISSUE TITLE
Banned Accounts

### ISSUE THREAD

**Issue by DevinD2323** [KebsCS/KBotExt#136]
I really enjoy using this application. I have seen people getting banned and I have also got one of my alt accounts banned for using this program. How do I use this program without getting banned? I saw something about compiling it myself but I do not know how to do that.

Any help would be appreciated

**Comment by KebsCS** [comment]
It's not bannable unless you're on Korean server, which is also not 100% confirmed

To compile:https://github.com/KebsCS/KBotExt#development
