### ISSUE TITLE
[idea]

### ISSUE THREAD

**Issue by sabala** [KebsCS/KBotExt#139]
can you put a method to change nickname with special character and check availability?

**Comment by KebsCS** [comment]
You can do it in a client already, pointless to have it in the tool

**Comment by sabala** [comment]
the client does not accept some characters that you can usually put as a glitch

**Comment by KebsCS** [comment]
> the client does not accept some characters that you can usually put as a glitch

I don't know if a bug like that exists, unless you share how to do it then I can add it

**Comment by sabala** [comment]
I don't know but I've seen another tool but in java that does what I told you, but other errors happen that end up disabling the app, you can see here: https://www.unknowncheats.me/forum/league-of-legends/577538-utilsv-easy-lobby-reveal-booster-refund.html

**Comment by KebsCS** [comment]
I decompiled it and it's literally the same as buying namechange in league store
