### ISSUE TITLE
Can't select Kha'zix to instalock

### ISSUE THREAD

**Issue by Jijuleta** [KebsCS/KBotExt#140]
Instead of a Kha'zix, KBotExt chooses the previous champion that was chosen to instalock.

**Comment by BennyExtreme** [comment]
Hi!
I can confirm.

After a bit of debugging:
[Here](https://github.com/KebsCS/KBotExt/blob/4e6916a8adf99fcdd1a1965ec95698a028169931/KBotExt/GameTab.h#L493C8-L493C8) we are comparing the names returned by the [lcu](https://github.com/KebsCS/KBotExt/blob/4e6916a8adf99fcdd1a1965ec95698a028169931/KBotExt/GameTab.h#L1023C106-L1023C106) (directly from the `alias` key) with the names extracted from the [communitydragon skins file](https://github.com/KebsCS/KBotExt/blob/4e6916a8adf99fcdd1a1965ec95698a028169931/KBotExt/Misc.h#L134C30-L134C30) (from the `loadScreenPath` key).

In this specific case the two values are not the same, from lcu is `"alias" : "Khazix"` so "Khazix", while from communitydragon is `"loadScreenPath": "/lol-game-data/assets/ASSETS/Characters/KhaZix/Skins/Base/KhazixLoadScreen.jpg"` so "KhaZix" with a capital 'Z'.

I think we could solve this by implementing the same strategy used in the communitydragon skins file to extract the champion name for lcu as well.

@KebsCS Please tell me what do you think, If you like the idea I will do a pr shortly.

Btw, sorry for the delay and hugs to everyone 😛🤗
