### ISSUE TITLE
cannot open source file "cpr/cpr.h"

### ISSUE THREAD

**Issue by window8** [KebsCS/KBotExt#143]
i got this error when buil in vs2022 and i did vcpkg install freetype:x86-windows-static or vcpkg install freetype:x64-windows-static, why?
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E1696	cannot open source file "cpr/cpr.h"	KBotExt	D:\C++\1\KBotExt\LCU.h	3

**Comment by JarrodTDy** [comment]
This is the same problem I'm having.

**Comment by bit-paper** [comment]
@window8 @JarrodTDy 
https://github.com/KebsCS/KBotExt/issues/130#issuecomment-1535689291

**Comment by window8** [comment]
> @window8 @JarrodTDy [#130 (comment)](https://github.com/KebsCS/KBotExt/issues/130#issuecomment-1535689291)

i tried many times but it still happens

**Comment by KebsCS** [comment]
> > @window8 @JarrodTDy [#130 (comment)](https://github.com/KebsCS/KBotExt/issues/130#issuecomment-1535689291)
> 
> i tried many times but it still happens

What's the error?

**Comment by Shucki** [comment]
VS2022: Right click the project -> Manage Nuget packages -> search "libcpr" -> install -> build now works.
