### ISSUE TITLE
cant instalock champions anymore

### ISSUE THREAD

**Issue by KBOTisAWESOME** [KebsCS/KBotExt#146]

**Comment by KebsCS** [comment]
Are you on prerelease?
What do you mean by "can't" what happens exactly?

**Comment by KBOTisAWESOME** [comment]
Yeah, im on the last release.
When i try to search for champion and click enter after i write championname it is just a empty space there, wont give me the champion.

**Comment by KebsCS** [comment]
Is it always empty or just for some champions?

**Comment by KBOTisAWESOME** [comment]
ive been trying alot of different champions, all of them is empty space after i click enter on that champion i write in

**Comment by KebsCS** [comment]
Does this also happen when you use mouse instead of enter?

**Comment by KBOTisAWESOME** [comment]
yes, when i click arrow down it is just a empty space the entire square

**Comment by KBOTisAWESOME** [comment]
it was the same on last release also

**Comment by KebsCS** [comment]
So is the combobox always empty or there are champions and they disappear after you enter their name?

**Comment by KBOTisAWESOME** [comment]
always empty when i click on arrow. 
but when I write the name it appears but as soon as I click enter what I have written it disappears

**Comment by KebsCS** [comment]
Is the skin data fetched? Did you try to switch tabs?

**Comment by KBOTisAWESOME** [comment]
im not sure what you ment now

**Comment by KBOTisAWESOME** [comment]
It is working now 👍  Thank you.

**Comment by KBOTisAWESOME** [comment]
:-D
