### ISSUE TITLE
Store tab to buy champs with IP / RP

### ISSUE THREAD

**Issue by Kumicoo** [KebsCS/KBotExt#147]
Hey kebs. Someone on a discord sent a pic of your tool with a "Store" tab where you could buy champs with IP/RP, select all 450 Champs, select champs and then mass buy them ETC. Where can i get that version?

**Comment by Kumicoo** [comment]
Tried my best to replicate what it looked like. There were more buttons etc but sadly i only opened the pic in discord and the guy deleted it. 

Second image is the guy who sent that picture on the discord.

![image](https://github.com/KebsCS/KBotExt/assets/35538818/ee9be18c-01a1-4594-9a88-ebfb5d8439ed)

![image](https://github.com/KebsCS/KBotExt/assets/35538818/9e7c95e8-84ae-4444-b981-7c7ca9dac1c2)

**Comment by Kumicoo** [comment]
Tried my best to replicate what it looked like. There were more buttons etc but sadly i only opened the pic in discord and the guy deleted it. 

Second image is the guy who sent that picture on the discord.

![image](https://github.com/KebsCS/KBotExt/assets/35538818/9f9bd10f-2fc4-4f67-9d47-a531277de38b)![image](https://github.com/KebsCS/KBotExt/assets/35538818/9e7c95e8-84ae-4444-b981-7c7ca9dac1c2)

**Comment by Kumicoo** [comment]
Nvm, here i found what it looked like in the discord cache luckily. 
![f_0000cf](https://github.com/KebsCS/KBotExt/assets/35538818/18348ab9-b526-42c8-a162-019912a7e43f)

**Comment by Kumicoo** [comment]
If thats not some hidden version, maybe possible to add this? Extremely useful for people like me who swap accounts to sell them weekly

**Comment by KebsCS** [comment]
It's open source, anyone can add anything they want to it, it's not some hidden version by me
