### ISSUE TITLE
issue with instalocking fiddlesticks

### ISSUE THREAD

**Issue by daegiri** [KebsCS/KBotExt#153]
the instalock isn't working for fiddlesticks, I think there's an issue with the name of the champion
it displays as 'FiddleSticks', and when I switch to another section (i.e Profile) this bug occurs.

![image](https://github.com/KebsCS/KBotExt/assets/54130825/072d5192-4e9b-47eb-bdf8-b7d76b63a8e5)

**Comment by BennyExtreme** [comment]
Hi!
I can confirm.

After a bit of debugging:
[Here](https://github.com/KebsCS/KBotExt/blob/4e6916a8adf99fcdd1a1965ec95698a028169931/KBotExt/GameTab.h#L493C8-L493C8) we are comparing the names returned by the [lcu](https://github.com/KebsCS/KBotExt/blob/4e6916a8adf99fcdd1a1965ec95698a028169931/KBotExt/GameTab.h#L1023C106-L1023C106) (directly from the `alias` key) with the names extracted from the [communitydragon skins file](https://github.com/KebsCS/KBotExt/blob/4e6916a8adf99fcdd1a1965ec95698a028169931/KBotExt/Misc.h#L134C30-L134C30) (from the `loadScreenPath` key).

In this specific case the two values are not the same, from lcu is `"alias" : "FiddleSticks"` so "FiddleSticks", while from communitydragon is `"loadScreenPath": "/lol-game-data/assets/ASSETS/Characters/Fiddlesticks/Skins/Base/FiddleSticksLoadscreen.jpg"` so "Fiddlesticks" with a lowercase 'S'.

I think we could solve this by implementing the same strategy used in the communitydragon skins file to extract the champion name for lcu as well.

@KebsCS Please tell me what do you think, If you like the idea I will do a pr shortly.

Btw, sorry for the delay and hugs to everyone 😛🤗
