### ISSUE TITLE
[SUGGESTION] Blank Level border selection

### ISSUE THREAD

**Issue by beepinboop** [KebsCS/KBotExt#155]
Hi, would it be possible to add a way to change your border to a blank/invisible one just like you can do with banners? I've seen many people with blank level borders but I have no idea how to actually do that. I imagine that it's similar to the banner one (make an api call asking for the "previous rank banner" without having a previous rank) but I'm not sure how to make these calls myself even after checking the lcu docs.
I've attached an image showing a profile with a "blank level border".
![f8mcwupfvq8a1](https://github.com/KebsCS/KBotExt/assets/132940458/997bebfe-83ce-4dfa-90fa-64edb89d0fdc)

**Comment by KebsCS** [comment]
I think that's for level 400/500+ since there isn't enough borders for levels

**Comment by beepinboop** [comment]
Ah, I apologize.
Never noticed how they're all high level, thought it was a similar bug to the banner one. Thanks for replying.
