### ISSUE TITLE
Lobby reveal failed

### ISSUE THREAD

**Issue by RadioactivePeaches** [KebsCS/KBotExt#161]
title. no clue why, tried reinstalling, maybe patched?

**Comment by KebsCS** [comment]
Only works when you get connected to the champion select patch, are you sure that wasn't the case? Also what do you mean by failed? Does it only open opgg with your name, doesn't open opgg at all, any error message?

**Comment by RadioactivePeaches** [comment]
It doesn't open any opgg whatsoever.
![Screenshot_12](https://github.com/KebsCS/KBotExt/assets/69229439/1c4784ed-62aa-4053-82a2-0fdd9fdf6f8d)

**Comment by RadioactivePeaches** [comment]
It can connect to champ select, because it would have said so otherwise.

**Comment by KebsCS** [comment]
If you go to custom tab, collapse the custom header and press on "Riot" button does it set up correct headers for you?

**Comment by changeevent** [comment]
> Yep, URL, Port, and Header are all filled in.

still working fine for me
