### ISSUE TITLE
Chech ban reason not working

### ISSUE THREAD

**Issue by 2b2tplayer** [KebsCS/KBotExt#168]
I get the whole html error saying I might be blocked, not sure if this is my issue or the program's, feel free to delete the comment if it's on my side

**Comment by KebsCS** [comment]
Riot changed something yesterday, will be fixed in the near future

**Comment by BennyExtreme** [comment]
They simply banned the user agent, they have been doing it for a long time.
I would recommend not to leave it static, they ban it every time on sight.
To avoid the problem [in other projects](https://github.com/BennyExtreme/valorant-match-history/blob/259980e4933149c7614d4f44359c549288a46eda/app/valApi.py#L36) we determine the user agent at runtime using a call to a third-party api for VALORANT to know what is the latest version of the Riot Client.

**Comment by KebsCS** [comment]
> They simply banned the user agent, they have been doing it for a long time. I would recommend not to leave it static, they ban it every time on sight. To avoid the problem [in other projects](https://github.com/BennyExtreme/valorant-match-history/blob/259980e4933149c7614d4f44359c549288a46eda/app/valApi.py#L36) we determine the user agent at runtime using a call to a third-party api for VALORANT to know what is the latest version of the Riot Client.

Thanks, fixed in https://github.com/KebsCS/KBotExt/commit/42146a759980b51583351b44f774eeef7362a987

**Comment by BennyExtreme** [comment]
It's not working again, and this time it's something bigger than the user agent.
