### ISSUE TITLE
ChampSelect Dodge not working

### ISSUE THREAD

**Issue by LeeFuuChang** [KebsCS/KBotExt#169]
clicked on 'Dodge' during ChampSelect phase and nothing happened

**Comment by KebsCS** [comment]
Any message at the bottom of the app?

**Comment by LeeFuuChang** [comment]
It shows this JSON, the `destination` in the data body is null, I think it's supposed to something else.
```json
{
	"body" : 
	{
		"body" : null,
		"clientId" : "nil",
		"correlationId" : "1041991786-348",
		"destination" : null,
		"headers" : {},
		"messageId" : "C0E83D71-F0D0-4578-9FBD-0B037F98A04C",
		"timeToLive" : 0.0,
		"timestamp" : 1692451150479.0
	},
	"typeName" : "flex.messaging.messages.AcknowledgeMessage"
}
```

**Comment by LeeFuuChang** [comment]
I've tried myself by posting through the same url and arguments as in your code.
Here's what I got (though `destination` is given, it still says that destination is required)
![image](https://github.com/KebsCS/KBotExt/assets/77952182/2408b4c8-323e-4bff-b5f0-511c1f361881)

**Comment by BennyExtreme** [comment]
> clicked on 'Dodge' during ChampSelect phase and nothing happened

To me works correctly as it is now

**Comment by BennyExtreme** [comment]
> I've tried myself by posting through the same url and arguments as in your code. Here's what I got (though `destination` is given, it still says that destination is required) ![image](https://user-images.githubusercontent.com/77952182/261827315-2408b4c8-323e-4bff-b5f0-511c1f361881.png)

![image](https://github.com/KebsCS/KBotExt/assets/75805898/1be7e40a-2b32-4eb1-8c8b-64b8b4b00b2b)

**Comment by LeeFuuChang** [comment]
```python
import requests as rq
import json
import urllib3
urllib3.disable_warnings()
headers = {"Authorization": "Basic ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"}
baseUrl = "https://127.0.0.1:9955"
print(json.dumps(rq.post(f'{baseUrl}/lol-login/v1/session/invoke?destination=lcdsServiceProxy&method=call&args=["", "teambuilder-draft", "quitV2", ""]', "", verify=False, headers=headers).json(), indent=4))
```
OK I think there's something wrong on my end and I don't know what it is.
I use the same code as you did and still doesn't work.
Is there anything known to cause this issue?
![image](https://github.com/KebsCS/KBotExt/assets/77952182/72536c55-6a89-47d4-af8e-e79e3374af4e)

**Comment by LeeFuuChang** [comment]
> > I've tried myself by posting through the same url and arguments as in your code. Here's what I got (though `destination` is given, it still says that destination is required) ![image](https://user-images.githubusercontent.com/77952182/261827315-2408b4c8-323e-4bff-b5f0-511c1f361881.png)
> 
> ![image](https://user-images.githubusercontent.com/75805898/261856754-1be7e40a-2b32-4eb1-8c8b-64b8b4b00b2b.png)

```python
import requests as rq
import json
import urllib3
urllib3.disable_warnings()
headers = {"Authorization": "Basic ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"}
baseUrl = "https://127.0.0.1:9955"
print(json.dumps(rq.post(f'{baseUrl}/lol-login/v1/session/invoke?destination=lcdsServiceProxy&method=call&args=["", "teambuilder-draft", "quitV2", ""]', "", verify=False, headers=headers).json(), indent=4))
```
OK I think there's something wrong on my end and I don't know what it is.
I use the same code as you did and still doesn't work.
Is there anything known to cause this issue?
![image](https://github.com/KebsCS/KBotExt/assets/77952182/72536c55-6a89-47d4-af8e-e79e3374af4e)

**Comment by LeeFuuChang** [comment]
> > I've tried myself by posting through the same url and arguments as in your code. Here's what I got (though `destination` is given, it still says that destination is required) ![image](https://user-images.githubusercontent.com/77952182/261827315-2408b4c8-323e-4bff-b5f0-511c1f361881.png)
> 
> ![image](https://user-images.githubusercontent.com/75805898/261856754-1be7e40a-2b32-4eb1-8c8b-64b8b4b00b2b.png)

```python
import requests as rq
import json
import urllib3
urllib3.disable_warnings()
headers = {"Authorization": "Basic ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"}
baseUrl = "https://127.0.0.1:9955"
print(json.dumps(rq.post(f'{baseUrl}/lol-login/v1/session/invoke?destination=lcdsServiceProxy&method=call&args=["", "teambuilder-draft", "quitV2", ""]', "", verify=False, headers=headers).json(), indent=4))
```
OK I think there's something wrong on my end and I don't know what it is.
I use the same code as you did and still doesn't work.
Is there anything known to cause this issue?
![image](https://github.com/KebsCS/KBotExt/assets/77952182/72536c55-6a89-47d4-af8e-e79e3374af4e)

**Comment by BennyExtreme** [comment]
Keep in mind that in custom it does not work.
Btw, what server are you on?

**Comment by LeeFuuChang** [comment]
> Keep in mind that in custom it does not work. Btw, what server are you on?

oh... rlly didn't know that
I play on Taiwanese server

and one more thing, how can I get that header Auth Basic thing that api key looking thing

**Comment by BennyExtreme** [comment]
You can get it through KBotExt in the "Custom" tab, clicking on "Custom Port/Header" and then "LCU" and in the headers there will also be the "Authorization" header.

Otherwise, there are 2 other methods:
- Lockfile:
  Usually you can find the file in the league installation directory, like `C:\Riot Games\League of Legends\lockfile` the format of this file is the following `<Process Name>:<Process ID>:<Port>:<Password>:<Protocol>`
  The username is always `riot`
- Launch arguments:
  Open a terminal and write the following command `wmic PROCESS WHERE name='LeagueClientUx.exe' GET commandline`.
  After doing that you can find the info that you need in the args, like:
  - `--app-port=<port>` is the port
  - `--remoting-auth-token=<password>` is the password
  - The username is always `riot`
 
Once you have this information you can compose your Authorization header:
- Create a string with "Basic "
- Encode in base64 the credentials in this format `riot:<password>`
- Append it to the auth string

In Python
```py
import base64

password = "<password>"

print("Basic " + base64.b64encode((f"riot:{password}").encode()).decode())
```
