### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by f1w** [KebsCS/KBotExt#172]
Riot Games seemed to have changed the data for the endpoint

https://127.0.0.1:{}/rso-auth/v1/session/credentials

most likely due to HCaptcha, any plan on fixing this?

**Comment by BennyExtreme** [comment]
Also the "Check ban reason" button has stopped working, again.

**Comment by JayBuckley7** [comment]
yup

**Comment by slowloriss** [comment]
The Error say
Malformed request

**Comment by gustavocsb** [comment]
Its working for me now, didnt change anything

**Comment by BennyExtreme** [comment]
Yes, I confirm.
They undid all the changes made to the API with today's update, wtf
