### ISSUE TITLE
Free Tristana +Riot Girl Skin

### ISSUE THREAD

**Issue by Glsa-china** [KebsCS/KBotExt#18]
Hey Bro！ I see youer Github “KbotExt”  I have a question for you
    
Free Tristana +Riot Girl Skin

Can this gift be changed into something else?
I've studied it roughly and I don't know if it can be realized, so let's ask. I want to change to zombie Ryze  XD!
Have a nice day!

We look forward to your reply!

**Comment by KebsCS** [comment]
No, it's not possible
