### ISSUE TITLE
Failed to get region, issue with multisearch

### ISSUE THREAD

**Issue by Vinositel** [KebsCS/KBotExt#181]
I have encountered a new issue this morning, when I tried to check my team with multisearch as ususal, it wouldn't open a link and the program tells me " Failed to get region". I reinstalled the program but the issue remained the same

**Comment by gustavocsb** [comment]
Same here

**Comment by KebsCS** [comment]
https://github.com/KebsCS/KBotExt/releases/tag/prerelease
