### ISSUE TITLE
the multi search doesnt work

### ISSUE THREAD

**Issue by wauso** [KebsCS/KBotExt#182]
the multi search function stopped working since patch 13.18 :( 
neither on op.gg and porofessor i cant look up on my team, pls fix it

**Comment by diyooor** [comment]
https://github.com/KebsCS/KBotExt/blob/3fb4229ab55aaf31c8b432e692e0089905e94887/KBotExt/GameTab.h#L1476C1-L1477C94

`std::string participants = cpr::Get(cpr::Url{ std::format("https://127.0.0.1:{}/chat/v5/participants/champ-select", LCU::riot.port) },
							cpr::Header{ Utils::StringToHeader(LCU::riot.header) }, cpr::VerifySsl{ false }).text;`

- https://lcu.vivide.re/
- https://github.com/HextechDocs/lcu-explorer

Seems that the endpoint used is deprecated in the most recent update.

**Comment by icyrs** [comment]
same problem, will this be fixed soon?

**Comment by KebsCS** [comment]
https://github.com/KebsCS/KBotExt/releases/tag/prerelease
