### ISSUE TITLE
Remove Border

### ISSUE THREAD

**Issue by yiyska** [KebsCS/KBotExt#190]
Will it be possible to post a request to make border into ranked border and if there's no current rank it will be invisible? 

I tried 
Method: POST
URL: /lol-challenges/v1/update-player-preferences
Body: 
{
	"crestBorder": "1" 
}
(I also tried "2" and "3") 
but it didn't work

**Comment by KebsCS** [comment]
Doesn't work. Will it be possible? I don't know, most likely no
