### ISSUE TITLE
Multi search fails to get names after patch 13.21

### ISSUE THREAD

**Issue by RJGY** [KebsCS/KBotExt#192]
![image](https://github.com/KebsCS/KBotExt/assets/54159414/d8cb3093-0c7f-43b9-8abd-e72d1010bd89)
See above image when trying to retrieve names via u.gg for multi search. This is on the pre-release version as well. Was working on patch 13.20. Guessing something in the back changed about how they hide names.

**Comment by andoryus** [comment]
yup can confirm, does not work on 13.21

**Comment by toprak** [comment]
@andoryus @RJGY was it able to search enemy too? (ingame) i need it.

**Comment by KebsCS** [comment]
Works fine for me on prerelease, does the issue still persists?

**Comment by andoryus** [comment]
> Works fine for me on prerelease, does the issue still persists? If so which server, I tested on euw

i test on OCE, also using prerelease

i think they changed something after the patch. i've used other similar programs to pull names which have now failed in getting names too.

**Comment by RJGY** [comment]
I am also on OCE using prerelease. Used to work on 13.20 but now fails on 13.21.

**Comment by RJGY** [comment]
> Works fine for me on prerelease, does the issue still persists? If so which server, I tested on euw

Still not working on OCE

**Comment by andoryus** [comment]
i still fail to get summoner names even with new preleases ..

**Comment by KebsCS** [comment]
Is it still happening on 1.5.4?

**Comment by KebsCS** [comment]
I think I fixed the issue, is it still happening on prerelease? https://github.com/KebsCS/KBotExt/releases/tag/prerelease

**Comment by RJGY** [comment]
Yes, the prerelease fixed the issues, thanks :)
