### ISSUE TITLE
1.5.4 Multi Search

### ISSUE THREAD

**Issue by andoryus** [KebsCS/KBotExt#200]
Unfortunately I'm still having problems with the program failing to get summoner names. 
I'm not quite sure if I'm doing anything wrong.

**Comment by KebsCS** [comment]
Is it still happening on prerelease? https://github.com/KebsCS/KBotExt/releases/tag/prerelease

**Comment by andoryus** [comment]
> Is it still happening on prerelease? https://github.com/KebsCS/KBotExt/releases/tag/prerelease

(sorry for late reply)
it works! thank you!
