### ISSUE TITLE
KBotExt is detected?

### ISSUE THREAD

**Issue by Yurichtofen** [KebsCS/KBotExt#201]
So recently I started using KBotExt again and so far I've gotten banned on 2 accounts quickly for "third party tools".

It's really weird that I've gotten banned on both a lvl 5 acc and some other old leveled acc.

Can anyone confirm that this also happends?

![obraz](https://github.com/KebsCS/KBotExt/assets/127675679/a33586b4-e7a4-4c5b-9f58-80a73bb428cd)

**Comment by KebsCS** [comment]
I know multiple people that have been using it daily and they're all fine. Did it happen to anyone else?

**Comment by Dorlander** [comment]
> I know multiple people that have been using it daily and they're all fine. Did it happen to anyone else?

nah, everything is fine
