### ISSUE TITLE
Kbot doesnt open or display

### ISSUE THREAD

**Issue by yetoria** [KebsCS/KBotExt#202]
Hello kbot doesnt open or display, i dont have anti virus on and I've added it to the Windows security exclusions, but it doesn't work; nothing happens when I try to open the software.

**Comment by NextStage1** [comment]
I've got same thing happening, been using kbot for a long time, working perfectly. Now in 1.5.4 and prerelease, application just closes after i open it. Version 1.5.3 still working.

https://github.com/KebsCS/KBotExt/assets/63713097/d82b1a8a-4905-4726-9917-5e92eb063106

**Comment by KebsCS** [comment]
We would need someone who experiences this issue to debug and identify the line that is causing the crash

**Comment by h4x0reL** [comment]
![image](https://github.com/KebsCS/KBotExt/assets/37605261/914dde2f-885b-4a71-91ed-f159ee9792a7)
does this helps ?

**Comment by h4x0reL** [comment]
Za pierwszym razem działa normalnie dopiero za drugim odpaleniem aplikacji występuje crash 
![image](https://github.com/KebsCS/KBotExt/assets/37605261/475c05b3-636d-42e4-9f73-25907c9de84f)

**Comment by changeevent** [comment]
> I've got same thing happening, been using kbot for a long time, working perfectly. Now in 1.5.4 and prerelease, application just closes after i open it. Version 1.5.3 still working.
> 2023-11-25_12-12-57.mp4

redownload new version, and stop using "Stream Proof" option. Do not check it

**Comment by NextStage1** [comment]
@changeevent yes, seem to be config issue. deleting current config and program make new one fixed it, so it works on the latest release and prerelease. weird thing tho, when building application with old "broken" config it seems to work fine with 0 issues. Well just happy it works now, thanks for the help:)

**Comment by KebsCS** [comment]
> @changeevent yes, seem to be config issue. deleting current config and program make new one fixed it, so it works on the latest release and prerelease. weird thing tho, when building application with old "broken" config it seems to work fine with 0 issues. Well just happy it works now, thanks for the help:)

Could you restore the deleted config and send it here so that I can check what was wrong and prevent it in the future?

**Comment by h4x0reL** [comment]
{
	"autoRename" : true,
	"checkPrerelease" : true,
	"customTab" : 
	{
		"header" : "",
		"method" : "",
		"port" : "",
		"requestText" : "",
		"urlText" : ""
	},
	"debugger" : false,
	"fontScale" : 1.0,
	"gameTab" : 
	{
		"autoAcceptEnabled" : false,
		"autoBanDelay" : 0,
		"autoBanEnabled" : false,
		"autoBanId" : 0,
		"backupId" : 0,
		"dodgeOnBan" : false,
		"indexFirstRole" : 0,
		"indexMultiSearch" : 0,
		"indexSecondRole" : 0,
		"instalockDelay" : 0,
		"instalockEnabled" : false,
		"instalockId" : 0,
		"instantMessage" : "",
		"instantMessageDelay" : 0,
		"instantMessageDelayTimes" : 0,
		"instantMessageTimes" : 1,
		"instantMute" : false,
		"sideNotification" : false
	},
	"ignoredVersions" : [],
	"infoTab" : 
	{
		"playerName" : ""
	},
	"invokeTab" : 
	{
		"args" : "",
		"destination" : "",
		"method" : ""
	},
	"leaguePath" : "C:/Riot Games/League of Legends/",
	"loginTab" : 
	{
		"language" : "en_US",
		"leagueArgs" : "--locale=en_US"
	},
	"noAdmin" : false,
	"streamProof" : true,
	"window" : 
	{
		"height" : 706,
		"width" : 1086
	}
}

Mine crash when the "Auto rename" and "check prerelase" are both ON.

**Comment by NextStage1** [comment]
@KebsCS old config
{
	"accounts" : 
	[
		"xxxxxxxxxxxxxx"
	],
	"amount" : "1",
	"apiKey" : "9e86178a0c8aa070229e81d7c89876ed",
	"autoRename" : true,
	"birth" : "01_01_2000",
	"birthType" : "RANDOM",
	"checkPrerelease" : true,
	"currentCaptcha" : "2CAPTCHA",
	"customTab" : 
	{
		"header" : "",
		"method" : "post",
		"port" : "",
		"requestText" : "{\"queueId\":870}",
		"urlText" : "lol-lobby/v2/lobby"
	},
	"customTemplate" : "${server}:${username}:${password}:${email}:${accountId}:${birth}:${creationDate} proxy: ${proxy}",
	"dbcPassword" : "",
	"dbcUsername" : "",
	"debugger" : false,
	"emailMask" : "@rito.plz",
	"emailSettingsType" : "RANDOM",
	"fontScale" : 1.0,
	"gameTab" : 
	{
		"autoAcceptEnabled" : true,
		"autoBanDelay" : 0,
		"autoBanEnabled" : true,
		"autoBanId" : 23,
		"backupId" : 0,
		"dodgeOnBan" : false,
		"indexFirstRole" : 2,
		"indexMultiSearch" : 3,
		"indexSecondRole" : 1,
		"instalockDelay" : 45,
		"instalockEnabled" : false,
		"instalockId" : 555,
		"instantMessage" : "",
		"instantMessageDelay" : 0,
		"instantMessageDelayTimes" : 0,
		"instantMessageTimes" : 10,
		"instantMute" : false,
		"sideNotification" : true
	},
	"ignoredVersions" : [],
	"infoTab" : 
	{
		"playerName" : ""
	},
	"invokeTab" : 
	{
		"args" : "",
		"destination" : "",
		"method" : ""
	},
	"leaguePath" : "C:/Riot Games/League of Legends/",
	"loginTab" : 
	{
		"language" : "en_US",
		"leagueArgs" : "--locale=en_US"
	},
	"noAdmin" : false,
	"passwordLength" : "10",
	"passwordOneForAll" : "",
	"passwordSetType" : "RANDOM",
	"selectedFont" : 0,
	"serverName" : "EUW",
	"streamProof" : false,
	"useCompact" : true,
	"useCustom" : false,
	"useFull" : true,
	"useProxy" : true,
	"usernameMax" : "12",
	"usernameMin" : "8",
	"usernameSetType" : "RANDOM",
	"window" : 
	{
		"height" : 537,
		"width" : 853
	}
}

**Comment by KebsCS** [comment]
Thank you all, fixed in 3622ee273af91361aa4fc4d8f834ca057bc98cb0
