### ISSUE TITLE
Clear Logs Feature

### ISSUE THREAD

**Issue by changeevent** [KebsCS/KBotExt#203]
Hi can you let me know which folders kbot clear logs is deleting?
I want to know for safety and also if I want to delete manually by hand, I can do it.
Please list all folders and files that kbot interact with computer when using the clear logs button

**Comment by KebsCS** [comment]
https://github.com/KebsCS/KBotExt/blob/main/KBotExt/Misc.h#L274

**Comment by changeevent** [comment]
thank you, I see that it did not delete Riot Games folder in %programdata%, might as well delete it

**Comment by KebsCS** [comment]
Thanks, added in https://github.com/KebsCS/KBotExt/commit/e533dbba4fdf2dc1144f365265790030289be183
