### ISSUE TITLE
Lobbyreveal not working in patch 14.2

### ISSUE THREAD

**Issue by qwerqwertyu** [KebsCS/KBotExt#217]
No idea what riot changed or if it's fixable but multi-search/lobbyreveal isn't working atm

**Comment by KebsCS** [comment]
Works fine for me on euw. Any error messages show up? Also use the prerelease version

**Comment by KebsCS** [comment]
Pushed prerelease to latest since not many people were using it https://github.com/KebsCS/KBotExt/releases/latest
