### ISSUE TITLE
Malformed Request

### ISSUE THREAD

**Issue by Rempacious** [KebsCS/KBotExt#226]
![image](https://github.com/KebsCS/KBotExt/assets/73411987/905a3bb7-32a8-49b6-abe9-2835967227cb)

**Comment by slowloriss** [comment]
i had same problem when using this for manager to loging my riot account.

**Comment by KebsCS** [comment]
Working again with the latest commit, available for download on prerelease:
https://github.com/KebsCS/KBotExt/releases/tag/prerelease
