### ISSUE TITLE
Can't login with saved accounts

### ISSUE THREAD

**Issue by remicm** [KebsCS/KBotExt#228]
The program opens the client but doesn't use the saved credentials

**Comment by yorik100** [comment]
Same issue

**Comment by 6oody** [comment]
+1

**Comment by slowloriss** [comment]
sometime works.

**Comment by remicm** [comment]
> sometime works.
It hasn't worked for me in 1 week. I tried different versions, different client languages ​​but without success. The program only launch the client

**Comment by 6oody** [comment]
i think if we can delete the whole bot and install it again it might work but i can't find it in app data to full uninstall it

**Comment by remicm** [comment]
> i think if we can delete the whole bot and install it again it might work but i can't find it in app data to full uninstall it


I think it just creates a config file in the same folder you have the executable in. Anyway, I tried with a new Windows user and also with a clean Windows installation from scratch without success.

**Comment by KebsCS** [comment]
Working again with the latest commit, available for download on prerelease:
https://github.com/KebsCS/KBotExt/releases/tag/prerelease
