### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by yinee-c** [KebsCS/KBotExt#23]
i dont know if its an gcc fault

im trying to compile it with gcc in visual studio code
`KBotExt.cpp (28, 54): cannot convert 'LPSTR' {aka 'char*'} to 'LPCWSTR' {aka 'const wchar_t*'}`

and an little warning:
`Settings.h (86, 30): 'Json::Reader::Reader()' is deprecated: Use CharReader and CharReaderBuilder instead [-Wdeprecated-declarations]`

**Comment by KebsCS** [comment]
For the first error change GetCommandLine to GetCommandLineW
The second one is just a warning, which can be ignored https://github.com/open-source-parsers/jsoncpp/issues/815

**Comment by yinee-c** [comment]
thanks
