### ISSUE TITLE
log in not working

### ISSUE THREAD

**Issue by ab220700** [KebsCS/KBotExt#232]
when i click on an account in kbot it opens the client but does not enter the log in credentials.

**Comment by ab220700** [comment]
Any updates to fix this issue?

**Comment by tragedyxxms** [comment]
maybe kbotext is discontinued and we as users don't know about it? xD

**Comment by ab220700** [comment]
> maybe kbotext is discontinued and we as users don't know about it? xD

would be a big shame

**Comment by KebsCS** [comment]
Working again with the latest commit, available for download on prerelease:
https://github.com/KebsCS/KBotExt/releases/tag/prerelease

Most of the features still work so it's not discontinued, I just don't update it as soon as the patch drops
