### ISSUE TITLE
issue with custom requests

### ISSUE THREAD

**Issue by arthures11** [KebsCS/KBotExt#238]
any example of how to do this? no matter how i try(ive tried with port/headers as well) it will return :

{
	"errorCode" : "RESOURCE_NOT_FOUND",
	"httpStatus" : 404,
	"message" : "Invalid function"
}

or 

{
	"errorCode" : "RESOURCE_NOT_FOUND",
	"httpStatus" : 404,
	"message" : "Invalid URI format"
}

![69ab0c6c87b1bb86ce123259db8956d0](https://github.com/KebsCS/KBotExt/assets/58474213/5d9ac28e-35e6-472a-9b12-58196b63b23f)

**Comment by KebsCS** [comment]
It is a Riot client endpoint, so collapse the Custom Port/Header, click on 'Riot,' and the URL will be https://127.0.0.1/chat/v4/friends

**Comment by arthures11** [comment]
> It is a Riot client endpoint, so collapse the Custom Port/Header, click on 'Riot,' and the URL will be https://127.0.0.1/chat/v4/friends

it has worked, but weirdly it needed like 10 attemps before it worked, first few attempts it showed the same thing - "message" : "Invalid URI format". 

Anyways, thank you

**Comment by arthures11** [comment]
bumping since i edited the message quite a bit

**Comment by KebsCS** [comment]
Looks like I forgot to add parameters to riotclient's data_info.json 
For now you can use GET https://127.0.0.1/help?target=ChatFriendRequestPost

**Comment by arthures11** [comment]
> Looks like I forgot to add parameters to riotclient's data_info.json For now you can use GET https://127.0.0.1/help?target=ChatFriendRequestPost

that works, tysm
