### ISSUE TITLE
Instant message

### ISSUE THREAD

**Issue by yinee-c** [KebsCS/KBotExt#24]
Instant message not working, before delay was added it was working, but now it's not.

**Comment by KebsCS** [comment]
The delay is to prevent sending a message too quickly, when you haven't connected to the chat yet. This patch the client's chat is very slow, so are you sure it is not the case? If so adjust the delay, as I haven't found a workaround for this problem yet

**Comment by yinee-c** [comment]
oh loool, it's working, my bad
