### ISSUE TITLE
hi I am using baseult, is it bannable?

### ISSUE THREAD

**Issue by sinankivanc3131** [KebsCS/KBotExt#249]
I have been using the lobby revealer app of baseult, unlike kbot it doesnt have 30+ functionalities, looks like just calls the official /champ-select riot api to get the names for your team. Anyone got banned for this? I have been using it for the last 1.5 years and never got banned but scared to use today

**Comment by KebsCS** [comment]
It uses the exact same method

**Comment by KebsCS** [comment]
Idk, you have to ask riot for that, not me. No idea why would the ban an app instead of fixing the broken endpoint
