### ISSUE TITLE
Skin Tab

### ISSUE THREAD

**Issue by Hollowcard565** [KebsCS/KBotExt#26]
Heya, I've been using this for days and I love it! There is just a small issue for the software though. It seems like whenever I click the "Skins" tab it'll just flat out crash. I'm not sure if there is any crash logs for that.

**Comment by KebsCS** [comment]
Make sure you're using the latest release, if so could I ask you to make a GET request to `/lol-inventory/v2/inventory/CHAMPION_SKIN` in the "Custom" tab and upload the response here?

**Comment by Hollowcard565** [comment]
Hello, seems like it's my fault on my end. The skins tab is working again! Thank you once again.
