### ISSUE TITLE
no league without KBot

### ISSUE THREAD

**Issue by serekAlmette** [KebsCS/KBotExt#27]
I am not able to start league or league client without first opening KBot ,can you help me ?

**Comment by KebsCS** [comment]
Maybe you enabled debugger and then changed executable path or filename. Try disabling debugger and see if that helps

**Comment by serekAlmette** [comment]
It didn't help, reinstalling didn't fix it either, I had this problem once and only full format on both of by disks helped. I don't want to do it again because i have a lot of games and it takes so long to download them

**Comment by KebsCS** [comment]
I have no idea how would that happen as simply opening it doesn't change anything to the executable. Unless you mean launching with the "Launch client" button, in which case your shortcut that you would normally launch league with was invalid

**Comment by serekAlmette** [comment]
I don't know either how it works by just opening it but I know I can open riot client and when I open league client from game folder it still don't want to open

**Comment by KebsCS** [comment]
Don't think that's a software issue then, as it doesn't change anything to the executable other than debugging, but as you said that was for sure disabled.

**Comment by serekAlmette** [comment]
so debugger is suppose to be hook into it self ?

**Comment by KebsCS** [comment]
League client looks for the debugger executable path on launch. If it doesn't exist it simply won't start

**Comment by serekAlmette** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/46404238/147831019-c36ee20d-d238-47c7-89ce-b32ae3e8df0a.png)
so why it does ?

**Comment by serekAlmette** [comment]
wait when i turn off debugger it works fine
