### ISSUE TITLE
Desinstal?

### ISSUE THREAD

**Issue by GrongosXD** [KebsCS/KBotExt#29]
I downloaded the application to test and when I uninstalled my game it wouldn't open, and when I open the game a CMD screen appears and I can't close it because my client closes together. What do I need to do to remove the program from my computer without my LoL bugging?

**Comment by KebsCS** [comment]
Press "Register debugger IFEO" in settings tab until it says "Hooked to: Nothing" and league will work again
Also duplicate of https://github.com/KebsCS/KBotExt/issues/27
