### ISSUE TITLE
A bug?

### ISSUE THREAD

**Issue by balasclava** [KebsCS/KBotExt#3]
Heyo! Do you have any idea how I can solve this?
![image](https://user-images.githubusercontent.com/71716568/120031127-c12c3480-bfce-11eb-8119-6ec1d39d3b73.png)

**Comment by KebsCS** [comment]
It doesn't work on win7/8 yet, or just launch league if you didn't do it already

**Comment by KebsCS** [comment]
Fixed in https://github.com/KebsCS/KBotExt/commit/6cce672b390e33722595901cc0d7d32fcd786fe9
