### ISSUE TITLE
windows 11 render problem

### ISSUE THREAD

**Issue by ionut1116** [KebsCS/KBotExt#30]
so you just need to run it on windodws 11 and it will start flickering like hell. and if you try to navigate it will render after 1 sec back the windows you had beffore

**Comment by KebsCS** [comment]
I've talked with people that use windows 11 and they had no problems, I don't know what could be the cause of that with the info you provided. Maybe there is a problem with directx 11 on your end, but I'm just guessing.

**Comment by ionut1116** [comment]
I could make a video when I get home. Or if you want I can show you on discord. Or if it saves logs somewhere I can provide that too. But I thought its this app cuz it's the only one that acts like this is you get me

**Comment by KebsCS** [comment]
Yes, a video would be nice. You can also try right clicking>Properties>Compatibility and running with compatibility mode for different version, or try the other settings.

**Comment by ionut1116** [comment]
That's the first thing I tried I fiddle with compatibility settings cuz I had win10 first and it was fine no problem. BTW no success with the compatibility settings, try a variety of combination of settings. I will get home soon

**Comment by ionut1116** [comment]
https://streamable.com/0nr5r4
im just clicking on the top row its works normal if it doesnt flash like that

**Comment by KebsCS** [comment]
Not enough information provided
