### ISSUE TITLE
Legacy mode returns 404 when logging in

### ISSUE THREAD

**Issue by dragitz** [KebsCS/KBotExt#31]
I'm currently trying to catch as many calls as I possibly can, so I gave the legacy mode a try.

The client in legacy mode, tries to send a POST request containing the login credentials when logging in, to the following url
 ``/lol-login/v1/session``

I'm unable to catch the login request in non legacy mode, and as far as I know I should send a valid jwt to an rso url instead of the above one, right?

**Comment by KebsCS** [comment]
This issue isn't related to this repository, but for non-legacy mode the riot client handles the auth.
