### ISSUE TITLE
Suggestions & improvements

### ISSUE THREAD

**Issue by itsalexq** [KebsCS/KBotExt#39]
Hello,
Some suggestions and improvements to make this the best tool possible for queueing in League of Legends :)

- Add dodge in the last millisecond (always allowing you to dodge perfectly at the end of timer to avoid LP losses & time penalty) as a tickbox
- Multiple clients (can only attach to one client currently)
- Auto re-queue
- Auto roles for ranked/draft

low prio
- Porofessor search (more useful than op.gg currently)
- Delay sliders on pick-intend & auto-ban (avoid uneccesarry suspicious behaviour)

**Comment by Pxprl** [comment]
Hello can help you with porofessor search and the other probably

**Comment by BennyExtreme** [comment]
@itsalexq
Hey, i implemented some of your suggestions/improvements, check out [my fork](https://github.com/BennyExtreme/KBotExt) if you want.

**Comment by itsalexq** [comment]
> @itsalexq Hey, i implemented some of your suggestions/improvements, check out [my fork](https://github.com/BennyExtreme/KBotExt) if you want.
> 
> * Auto roles for ranked/draft
> * Porofessor search (more useful than op.gg currently)
> * Delay sliders on pick-intend & auto-ban (avoid uneccesarry suspicious behaviour)

Hello, thanks for the contribution. Would it be possible to add the last second dodge?

**Comment by KebsCS** [comment]
Porofessor search added in 1d05f6e6eaf6258d35275a2a632fc9ee7c831800. If I decide to add auto requeue I'll give an update in #36 
Feel free to suggest more features :)

**Comment by itsalexq** [comment]
> Multiple clients, roles for ranked/draft and settings for auto ban added in https://github.com/KebsCS/KBotExt/releases/tag/1.5.0
> 
> Last second dodge might be not possible, as client doens't share the timer and the time it takes to dodge mostly depends on pc and server's speed.

Hello,

Thanks for adding all the things.

Auto dodge doesn't have to be perfect, you can even make it adjustable from the players PoV. So it dodges more/less precise and depending on your own setup you know where it will dodge.

Thanks!

**Comment by Dorlander** [comment]
please add Cyrillic support to instant message

**Comment by Dorlander** [comment]
> Porofessor search added in [1d05f6e](https://github.com/KebsCS/KBotExt/commit/1d05f6e6eaf6258d35275a2a632fc9ee7c831800). If I decide to add auto requeue I'll give an update in #36 Feel free to suggest more features :)

hi, can u add mass friend inviter? ctrl+v/ctrl+c one button
