### ISSUE TITLE
name bug

### ISSUE THREAD

**Issue by Geromo94** [KebsCS/KBotExt#4]
![image](https://user-images.githubusercontent.com/37875880/121157593-47bcfd80-c87c-11eb-9314-e760050975c6.png)

**Comment by Geromo94** [comment]
> In newest release (1.3.0) you can change font to one that supports your league client's language
> 
> ![image](https://user-images.githubusercontent.com/22469895/121257447-fe85a180-c8ad-11eb-88fd-f03ac2d3c2a8.png)

Thanks! 

https://i.gifer.com/Aq.gif

**Comment by y3541599** [comment]
You have to add the font and change to it by yourself

**Comment by KebsCS** [comment]
You have to change the font by yourself, the one I used is msgothic.ttc and it is installed on windows by default

**Comment by Geromo94** [comment]
Segoi UI.ttf supports Cyrillic, but still name ????

**Comment by KebsCS** [comment]
I fixed it and Cyrillic support will be added in the next update

**Comment by Geromo94** [comment]
> Я исправил это, и в следующем обновлении будет добавлена ​​поддержка кириллицы.

Thank you ^_^

**Comment by KebsCS** [comment]
Fixed in 1.3.1
