### ISSUE TITLE
Champions tab proplem

### ISSUE THREAD

**Issue by Khaledmohamed1988** [KebsCS/KBotExt#40]
Its perma crash the app after click
need a fix

**Comment by dongerlel** [comment]
+1 it crashed for me too

**Comment by KebsCS** [comment]
Fixed in 953ec118f4e6c37ae080f028e8e1cb6ca0ff6960

**Comment by KebsCS** [comment]
Fixed in 953ec118f4e6c37ae080f028e8e1cb6ca0ff6960

**Comment by azorek777** [comment]
@KebsCS is it possible to upload a fixed version as .exe? I tried myself but it opens with console window :/

**Comment by KebsCS** [comment]
> @KebsCS is it possible to upload a fixed version as .exe? I tried myself but it opens with console window :/

Compile in Release mode (with NDEBUG flag)

**Comment by Khaledmohamed1988** [comment]
Bro u cant make a new version with update fix since not everyone can handle this without any knowledge about what you talking about the most users looking for the final easy interface as in releases

**Comment by dongerlel** [comment]
+1
come on make a new exe version for pleb

**Comment by Pxprl** [comment]
@dongerlel @Khaledmohamed1988 dm me on disc Lasse#1111 if u want an updated one

**Comment by BennyExtreme** [comment]
@azorek777 @Khaledmohamed1988 @dongerlel
You can check [my fork](https://github.com/BennyExtreme/KBotExt) if you want.
