### ISSUE TITLE
Remove Badges

### ISSUE THREAD

**Issue by flezus** [KebsCS/KBotExt#42]
I don't know if it's available on the Client, but there could be a method of removing the Badges that keep appearing on the profile, this horrible thing

**Comment by BennyExtreme** [comment]
@flezus
Hey, i implemented it, you can check [my fork](https://github.com/BennyExtreme/KBotExt) if you want.

**Comment by KebsCS** [comment]
> @flezus Hey, i implemented it, you can check [my fork](https://github.com/BennyExtreme/KBotExt) if you want.

Good job :) Would you mind making a pull request?

**Comment by BennyExtreme** [comment]
> > @flezus Hey, i implemented it, you can check [my fork](https://github.com/BennyExtreme/KBotExt) if you want.
> 
> Good job :) Would you mind making a pull request?

Done!
Please read the [comment](https://github.com/KebsCS/KBotExt/commit/953ec118f4e6c37ae080f028e8e1cb6ca0ff6960#r85163531) i left in your last commit, thank you :)

**Comment by KebsCS** [comment]
> > > @flezus Hey, i implemented it, you can check [my fork](https://github.com/BennyExtreme/KBotExt) if you want.
> > 
> > 
> > Good job :) Would you mind making a pull request?
> 
> Done! Please read the [comment](https://github.com/KebsCS/KBotExt/commit/953ec118f4e6c37ae080f028e8e1cb6ca0ff6960#r85163531) i left in your last commit, thank you :)

Thank you, would you mind making a pull request with other changes too?

**Comment by BennyExtreme** [comment]
> > > > @flezus Hey, i implemented it, you can check [my fork](https://github.com/BennyExtreme/KBotExt) if you want.
> > > 
> > > 
> > > Good job :) Would you mind making a pull request?
> > 
> > 
> > Done! Please read the [comment](https://github.com/KebsCS/KBotExt/commit/953ec118f4e6c37ae080f028e8e1cb6ca0ff6960#r85163531) i left in your last commit, thank you :)
> 
> Thank you, would you mind making a pull request with other changes too?

#46 #47 #48 #49 #50
