### ISSUE TITLE
[not error] Make new release pls

### ISSUE THREAD

**Issue by fagsdgadsgasdgasd** [KebsCS/KBotExt#54]
I cannot compile cuz v141 platform tools =(

**Comment by yunyty** [comment]
+1

**Comment by KebsCS** [comment]
Hi, the project should build regardless of platform tools version. Although a new update will be uploaded in the near future.

**Comment by fagsdgadsgasdgasd** [comment]
> Hi, the project should build regardless of platform tools version. Although a new update will be uploaded in the near future.

Unfortunately std::format has only in c++20 language standard

**Comment by ricexkss** [comment]
just modify your VS install
![image](https://user-images.githubusercontent.com/79546029/197459391-a1dce190-1617-4c8e-9815-f2f7ee32d12c.png)

**Comment by KebsCS** [comment]
Released https://github.com/KebsCS/KBotExt/releases/tag/1.5.0
