### ISSUE TITLE
instant message doesn't work

### ISSUE THREAD

**Issue by mgiedz** [KebsCS/KBotExt#56]
tried tweaking delays, etc. only works like once in 10 launches.

**Comment by myfirstevercode** [comment]
it works, make sure the delay is 2000

**Comment by KebsCS** [comment]
Fixed in https://github.com/KebsCS/KBotExt/commit/94d13918558799e7704bd9fa50505362cdc7d47f

Now, it will first check if it's connected to champion select, and then apply the delay, so no need to look for a sweetspot
