### ISSUE TITLE
How to use mastery changer

### ISSUE THREAD

**Issue by whiteasvoid** [KebsCS/KBotExt#60]
How does Mastery Changer works? It doesnt seem to do anything in the profile, im not sure if its bugged or not but it doesnt seem to be working, or im using it wrong?

**Comment by KebsCS** [comment]
Just checked on NA and EUW, and it does work
![image](https://user-images.githubusercontent.com/22469895/201417410-07a9e5f3-de7d-4203-9b78-8b21db157320.png)

**Comment by whiteasvoid** [comment]
Oh, so thats what it is, thank you for letting me know, im sorry, since there is no guide or something to tell how it works.

Thank you for the response ^^ Great program btw
