### ISSUE TITLE
cyrillic support

### ISSUE THREAD

**Issue by Dorlander** [KebsCS/KBotExt#71]
cyrillic support in instant message window

**Comment by KebsCS** [comment]
Cyrillic is supported, even though the default shows "?" instead of the correct characters, it still sends correctly in the chat box. If you also want to see it in the program, you have to change the font in the Settings Tab

**Comment by Dorlander** [comment]
> Cyrillic is supported, even though the default shows "?" instead of the correct characters, it still sends correctly in the chat box. If you also want to see it in the program, you have to change the font in the Settings Tab

it looks like this to me
![изображение_2023-01-03_082454828](https://user-images.githubusercontent.com/61416392/210303998-fb6cb27d-3905-4eaa-849c-7ca063656ab9.png)
