### ISSUE TITLE
After changing language, this tool broke my game completely

### ISSUE THREAD

**Issue by Kumicoo** [KebsCS/KBotExt#74]
Changed the language, wanted to change it back, didnt work, now my game wont start, i tried reinstalling but it will always say "Update" in the riot client and nothing happens, i cant reinstall or uninstall league of legends. Repair files and hextech repair tool also dont work. This completely broke my game. All i did was change the language and then try to change it back to english.

**Comment by KebsCS** [comment]
Is the league client not starting, or is it because you have only Update button instead of Play?

**Comment by Kumicoo** [comment]
Riot Client starts and it shows update on the bottom left, clicking it either does absolutely nothing, or changes it to the circle, but it will never start an update. Cant uninstall league from the program menu either. I used an uninstaller to remove league and any traces and now it works, but the language thing certainly completely broke it

**Comment by Kumicoo** [comment]
Hextech repair tool did nothing, scan repair did nothing it was completely bricked

**Comment by KebsCS** [comment]
The language changer just adds an argument to launch options, so there's no way that was it. I've had the same problem and I fixed it by cleaning logs from settings tab, but no idea what caused it

**Comment by Kumicoo** [comment]
Maybe its just Riot client fucking up when you change to a language thats not supported in your region? I did Ja_JP

**Comment by KebsCS** [comment]
Changing language doesn't cause it, I don't know what does.
Closing since it's fixed
