### ISSUE TITLE
Add details to the executable

### ISSUE THREAD

**Issue by ReprimandedKaito** [KebsCS/KBotExt#77]
Currently the executable doesn't have a **Product name** and, more importantly, a **Product version**.
This is useful to know what version of the file I have, esp since this piece of information is not shown in-app.

![Executable details](https://user-images.githubusercontent.com/116013630/212492206-ba60b5ec-1b0a-40ef-ba19-a77822004b3b.png)

**Comment by KebsCS** [comment]
Hi, thank you for the suggestion, I've added it in-app https://github.com/KebsCS/KBotExt/commit/dc143fea2e385e6964935313d78ddf47a5a30936
