### ISSUE TITLE
The app doesn't recognize the accounts I'm on, so it won't work.

### ISSUE THREAD

**Issue by reacter1** [KebsCS/KBotExt#80]
I've used the app before on my old laptop, but now that I have a new PC it stopped recognizing the accounts I'm on and therefore not working.

I've tried two things: Disabling windows defender and turning Valorant anti-cheat off. 

This is how I see the app:
![image](https://user-images.githubusercontent.com/123027620/213304033-32fb1446-8351-454a-b814-dd2be7044320.png)

I would like to know if you have a "fix" to this problem!

**Comment by KebsCS** [comment]
Hi, version 0.0.0 happens when the app can't send any http request. That means something is blocking it, most likely it's antivirus or firewall

**Comment by reacter1** [comment]
I didn't mess with the firewall do you have any clue what to do?

**Comment by KebsCS** [comment]
> I didn't mess with the firewall do you have any clue what to do?

![image](https://user-images.githubusercontent.com/22469895/213322149-6fbac5e3-57ea-4fa6-8d6a-ff7a7bcf4d28.png)

Also, you can try redownloading it and then making exceptions for it on antivirus and firewall

**Comment by reacter1** [comment]
edownloaded it did the firewall thing, widowns defender is off and no luck.

**Comment by behrouzi123** [comment]
Is this tool bannable since it injects into the client?

**Comment by KebsCS** [comment]
> edownloaded it did the firewall thing, widowns defender is off and no luck.

Then it has to he something else blocking it. Error 12158 means ERROR_INTERNET_UNABLE_TO_CACHE_FILE


> Is this tool bannable since it injects into the client?

No it's not bannable and it doesn't inject anything

**Comment by reacter1** [comment]
The funny thing is I can click on "blind pick" and it will create one. Keep in mind that it still says that it isn't connected to any accounts.

**Comment by KebsCS** [comment]
> The funny thing is I can click on "blind pick" and it will create one. Keep in mind that it still says that it isn't connected to any accounts.

That's weird, maybe it didn't run as administrator?

**Comment by reacter1** [comment]
It has the thing that makes it run every time, I'm reinstalling league atm to see if it fixes.

**Comment by reacter1** [comment]
> It has the thing that makes it run every time, I'm reinstalling league atm to see if it fixes.

Did not work and still doesn't connect to the account I'm on, very sad.

**Comment by reacter1** [comment]
Tried another feature that works, I can log in through the app and it still does not connect

Is this the thing firewall thing you were talking about?
![Screenshot_2](https://user-images.githubusercontent.com/123027620/213521217-ece2efa7-17ae-48fc-869a-7c851bfeb38d.png)

And is it normal for it to show that the version is 0.0.0?
![image](https://user-images.githubusercontent.com/123027620/213521422-da51ad0b-04c1-41a4-bc1d-4130edaa963a.png)

**Comment by KebsCS** [comment]
> Tried another feature that works, I can log in through the app and it still does not connect
> 
> Is this the thing firewall thing you were talking about? ![Screenshot_2](https://user-images.githubusercontent.com/123027620/213521217-ece2efa7-17ae-48fc-869a-7c851bfeb38d.png)
> 
> And is it normal for it to show that the version is 0.0.0? ![image](https://user-images.githubusercontent.com/123027620/213521422-da51ad0b-04c1-41a4-bc1d-4130edaa963a.png)

Version 0.0.0 means it can't send a request to https://ddragon.leagueoflegends.com/api/versions.json

Could you send in Custom Tab request like this one and post here the result?
Method: GET
Url: https://ddragon.leagueoflegends.com/api/versions.json
Body: _empty_
Port: 443
Headers: _empty_

**Comment by antonkostas** [comment]
> Could you send in Custom Tab request like this one and post here the result? Method: GET Url: https://ddragon.leagueoflegends.com/api/versions.json Body: _empty_ Port: 443 Headers: _empty_

I can. Got the same issue.

HttpSendRequestA failed. Last error: 12158

**Comment by KebsCS** [comment]
There's almost no information on the internet about that error. It might have something to do with the pc being unable to cache if the file exceeds some size, but honestly I have no idea. If it's a fresh pc, maybe you're missing some drivers or some configuration. Let me know if you manage to fix it

**Comment by antonkostas** [comment]
Alright, here's a list of things I tried to no avail:

- Checked internet connection
- Disabled: 
1. proxy settings
2. firewall
3. antivirus software (windows defender) 
- Didn't have to update network adapter drivers
- With Default DNS settings & Google DNS

Hope someone figures it out.

**Comment by Vinositel** [comment]
Hi there! I have the same problem it shows version 0.0.0 and it doesnt connect. It is mainly multi-search that doesnt work, other stuff like dodge, pick role, switch from ranked to normal or aram works, but multi search doesnt

**Comment by HalfDragonLucy** [comment]
Same problem here

**Comment by KebsCS** [comment]
Is it also the case on the prerelease? https://github.com/KebsCS/KBotExt/releases/tag/prerelease

Also what features don't work, is it just multi-search and skin data fetching?

**Comment by HalfDragonLucy** [comment]
> Is it also the case on the prerelease? https://github.com/KebsCS/KBotExt/releases/tag/prerelease
> 
> Also what features don't work, is it just multi-search and skin data fetching?

Upon trying the pre-release I tested all the features one by one to see which one did- did not work.

#  Status Bar
- [X] Version number
![image](https://user-images.githubusercontent.com/62443788/220162348-2d9530a3-0885-4508-b2a9-cda0b868215d.png)
- [ ] Fetching skin data
![image](https://user-images.githubusercontent.com/62443788/220162450-ac045226-f6df-478b-bbaa-0e4449243bd9.png)


# Game
|Passed|Failed|Unknow|
|--|--|--|
|Blind Pick | Practice Tool | Nexus Blitz
|Draft Pick
|Solo/Duo
|Flex
|Aram
|Arurf
|TFT Normal
|TFT Ranked
|TFT Hyper Roll
|TFT Double Up 
|TFT Tutorial
|Practice Tool 5v5
|Clash
|Tutorial 1
|Tutorial 2 
|Tutorial 3
|Intro Bots
|Beginner Bots
|Intermediate Bots
|Custom Blind
|Custom Aram

Whatever I selected into the **games** selection gave me the error code `12158` despite working.

I couldn't test to **add bots** to the custom lobbies as the bot selection was showing no entry.
![image](https://user-images.githubusercontent.com/62443788/220162650-359ba458-8d08-4035-ba56-f7ac041e2aaa.png)

- [x] **Picks Roles** worked.
- [ ] **Change Runes** didn't worked and showed the error `Failed to fetch op.gg runes`
- [ ] **Blue/Red Side notifications** showed nothing.

>

- [x] **Start Queue** worked.
- [x] **Dodge** worked.
- [ ] **Multi-Search** didn't worked on a lobby with visible names, and showed the error `Champion select not found`

>

- [ ] **Auto Accept** started the search for an game upon trying to switch lobbies during the test. Furthermore it didn't worked during game search.
- [ ] **Invite everyone to lobby** didn't worked, no error code.
- [ ] **Refund last purchase** N/A

>

- [ ] **Instant message** didn't worked, no error code.
- [ ] **Delay** N/A
- [ ] **Time(s)** N/A
- [ ] **Delay between msgs** N/A

>

- [ ] **Instalock champ/Back-up pick/Auto ban** didn't worked,  showed "error" `Champion data is still being fetch`
![image](https://user-images.githubusercontent.com/62443788/220162823-7afaae2f-7e95-4ea1-8116-7427e60dbb2f.png)

# Profiles

- [x] **Status** worked.
- [x] **Online/Mobile/Away/Offline** worked.

>

- [x] **Rank Submit/Empty** worked.
- [ ] **Invisible banner** didn't worked, no error code.

>

- [ ] **Challenge Empty/Copy/Glitched** didn't worked, no error code.

>

- [x] **Mastery** worked.
- [x] **Icon** worked.
- [ ] **Background** didn't worked,  showed "error" `Champion data is still being fetch`

 # Info

- [ ] **Input player name** didn't worked, showed error `12029`
- [ ] **Invite to lobby** didn't worked, no error code.
- [ ] **Invite to friends** didn't worked, no error code.

>

- [ ] **Add to block list** didn't worked, no error code.
- [ ] **Copy to clipboard** didn't worked, showed error `12029`

# Champs

- [ ] **Champions owned** didn't worked, no error code.
- [ ] **Sort by Alphabetically/Purchase date/Mastery points/ID** N/A

# Skins

- [ ] **Skins owned** didn't worked, no error code.
- [ ] **Sort by Alphabetically/Purchase date/ID** N/A

# Misc

- [x] **Launch another client** worked.
- [ ] **Launch legacy client** started the default client with infinite loading, error code `12158`

>

- [x] **Restart UX** worked.
- [x] **Close client** worked.

>

- [ ] **Accept all friend requests** didn't worked, error code `Failed to parse JSON` (with 1 friend request pending)
- [ ] **Delete all friend requests** didn't worked, error code `Failed to parse JSON` (with 1 friend request pending)
- [ ] **Remove all friends from folder..** didn't worked, error code `Failed to parse JSON`

>

- [ ] **In-game minimap scale** didn't worked, error code `12158`

>

- [ ] **Disenchant all** N/A (had nothing to test it)
- [ ] **Champion name to ID** didn't worked, no error code.
- [ ] **Check email of the account** didn't worked, error code `12158`

Upon force-forcing the client and restarting, **KBotExt** stopped answering completely until I shutted it down with task manager.

**Comment by KebsCS** [comment]
@HalfDragonLucy 
Thanks a lot for this. Seems like "GET" requests don't work on http**s** requests, which doesn't make sense. Could you test it for me? In custom tab make a request with 
Method: GET or POST  (test both)
URL: /lol-lobby/v2/lobby
Body: empty
And what results do you receive?

**Comment by HalfDragonLucy** [comment]
> @HalfDragonLucy Thanks a lot for this. Seems like "GET" requests don't work on http**s** requests, which doesn't make sense. Could you test it for me? In custom tab make a request with Method: GET or POST (test both) URL: /lol-lobby/v2/lobby Body: empty And what results do you receive?

Both gave me the error `12007` but after restarting the app it gave me these:

`GET` `/lol-lobby/v2/lobby`
```json
{
	"errorCode" : "RPC_ERROR",
	"httpStatus" : 404,
	"implementationDetails" : {},
	"message" : "LOBBY_NOT_FOUND"
}
```
`POST` `/lol-lobby/v2/lobby`
```json
{
	"errorCode" : "RPC_ERROR",
	"httpStatus" : 400,
	"implementationDetails" : {},
	"message" : "A value for 'lobbyChange' is required."
}
```

**Comment by KebsCS** [comment]
Could you check the newest prerelease? https://github.com/KebsCS/KBotExt/releases/tag/prerelease
I've disabled http caching so hopefully it fixes error 12158

**Comment by HalfDragonLucy** [comment]
I checked the features that showed up the error code `12158` and it is **still** displaying the same error code

> Whatever I selected into the games selection gave me the error code `12158` despite working.
> **Launch legacy client** started the default client with infinite loading, error code `12158`
> **In-game minimap scale** didn't worked, error code `12158`
> **Check email of the account** didn't worked, error code `12158`

**Comment by KebsCS** [comment]
No idea then, what windows version are you on?

**Comment by BennyExtreme** [comment]
> No idea then, what windows version are you on?

Windows 10 21H1 64-bit operating system (Build 19043.1149)

**Comment by HalfDragonLucy** [comment]
Thanks @BennyExtreme

**Comment by BennyExtreme** [comment]
## Apparently we have found a solution to the problem

Steps:
* Close KBotExt if you have it open
* Open "Internet Properties" (`inetcpl.cpl`)
* Go to "Advanced" tab
* Click the "Restore advanced settings" button
* Save the changes and close the window by clicking the "OK" button
* Try to open KBotExt again, it should work.

**Comment by KebsCS** [comment]
@reacter1 @antonkostas @Vinositel 
Did it fix the problem?

**Comment by KebsCS** [comment]
Made an update https://github.com/KebsCS/KBotExt/releases/tag/prerelease
Let me know if you get the pop-up window and it fixes the issue @reacter1 @antonkostas @Vinositel

**Comment by antonkostas** [comment]
> Made an update Let me know if you get the pop-up window and it fixes the issue @antonkostas 

Fixed it for me! 👍

**Comment by KebsCS** [comment]
Thanks a lot @HalfDragonLucy @BennyExtreme for the help
