### ISSUE TITLE
Disenchant all wards doesn't work

### ISSUE THREAD

**Issue by Twiston-7** [KebsCS/KBotExt#82]
As title suggests. 

https://user-images.githubusercontent.com/97396676/213693991-690f19ed-49cd-40c2-acb5-8d3641a47187.mp4

**Comment by myfirstevercode** [comment]
make sure the settings are configured correctly

ex: C:\Riot Games\League of Legends\Game

**Comment by Twiston-7** [comment]
> make sure the settings are configured correctly unless its already working on champ and skins
> 
> ex: C:\Riot Games\League of Legends\Game

It worked on eternals before, so that's not the issue I suppose

**Comment by KebsCS** [comment]
Thank you for the report. I don't have an account with ward skins to test it, could you send in Custom Tab request like this one and post here the result?
Method: GET
Url: /lol-loot/v1/player-loot-map
Body: _empty_
Without pressing on "Custom Port/Header"

**Comment by KebsCS** [comment]
Fixed in https://github.com/KebsCS/KBotExt/commit/a639b664093d965b15b8a09b30ed1a861fbd3ef4
