### ISSUE TITLE
Attempting to add a bot crashes the program if no champion to pick is selected

### ISSUE THREAD

**Issue by Twiston-7** [KebsCS/KBotExt#83]
https://user-images.githubusercontent.com/97396676/213695060-f08303a3-05e5-42e6-9244-b59e54c78a25.mp4

**Comment by Twiston-7** [comment]
Same happens with "Hard" difficulty

**Comment by KebsCS** [comment]
Thank you for the report, fixed in https://github.com/KebsCS/KBotExt/commit/a639b664093d965b15b8a09b30ed1a861fbd3ef4
