### ISSUE TITLE
Refund Last Purchase not working

### ISSUE THREAD

**Issue by thienha1** [KebsCS/KBotExt#85]
I tried buy Champion with RP then go to practice and picked champion as purchased and press this button and show error like this:
```
{
	"status" : 
	{
		"message" : "Forbidden",
		"status_code" : 403
	}
}
```
What does it mean? Patched?

**Comment by KebsCS** [comment]
Hi, I've tested it and it works for me on euw, eune and na. What server are you on and do you have at least 1 refund remaining?

**Comment by thienha1** [comment]
> Hi, I've tested it and it works for me on euw, eune and na. What server are you on, and do you have at least 1 refund token remaining?

I'm playing in SEA server (Singapore), and yea I have 2 refund token remaining

**Comment by KebsCS** [comment]
Thank you, fixed in https://github.com/KebsCS/KBotExt/commit/99866e735ce5d65ea25428e9abeeea37230a36f9
