### ISSUE TITLE
Suggestion: instadodge based on marked players

### ISSUE THREAD

**Issue by RadioactivePeaches** [KebsCS/KBotExt#86]
You can mark a player on your team as permadodge, if theyre on your team or has less than 45%wr then dodge the game

**Comment by KebsCS** [comment]
If you add someone to blocklist, league shows you a notification in champion select and you can dodge yourselves. If it did dodge automatically, it would just cause confusion. The tool is mostly to allow using features that aren't in the client or automate some long tasks e.g disenchanting a lot of shards in loot, dodging is just 1 click.
