### ISSUE TITLE
VirusTotal

### ISSUE THREAD

**Issue by Elvast** [KebsCS/KBotExt#90]
Care to explain? 

![image](https://user-images.githubusercontent.com/122123219/215279829-bd68a544-c8e6-437e-a00b-62f26b43c35c.png)

**Comment by KebsCS** [comment]
Gamehacks are often recognized as or confused with malware by antivirus services due to the way these programs interact with system processes, memory and the operating system itself. The source is public, so if you're worried that the release differs from it, you can build it yourself.
