### ISSUE TITLE
Allow special characters in instant messages and profile status

### ISSUE THREAD

**Issue by hotspicytaco** [KebsCS/KBotExt#97]
Hello! I can't thank you enough for this tool.

I'd love to see support for more characters, these could be emotes from Windows 10 or characters from this list:

https://www.fileformat.info/info/charset/UTF-8/list.htm

![image](https://user-images.githubusercontent.com/3945842/219514367-a58b37b3-ddd6-4f52-b852-96b134df0d91.png)

**Comment by KebsCS** [comment]
Hi, thank you for the suggestion
Added in https://github.com/KebsCS/KBotExt/commit/1c5accc7019a6e0fb3bfb5a6fc95856942d365b7
![image](https://user-images.githubusercontent.com/22469895/219870088-f0a26d94-18fe-4963-8bda-b5d319ddb9ab.png)
