### ISSUE TITLE
Error when compiling 

### ISSUE THREAD

**Issue by myfirstevercode** [KebsCS/KBotExt#98]
Im having problem trying to compile the latest changes:
![image](https://user-images.githubusercontent.com/15106245/219904986-b7b6245b-4524-4684-ace8-36f94885b602.png)

I can compile fine back in v1.5.2 with minimal errors, tried creating ft2build.h from [here](https://github.com/servo/libfreetype2/blob/master/freetype2/include/ft2build.h) then i get more errors, 
![image](https://user-images.githubusercontent.com/15106245/219905120-6af55581-434c-4add-ab29-386afe68efc1.png)

would also love if you can make a simple tutorial how to install and compile using the code with all the requirements included since maybe i might be missing some settings or files to make the compiling smooth

**Comment by KebsCS** [comment]
Hi, the new version uses freetype, which requires the lib to be installed. I will add short compilation guide to the readme soon.

This are the commands to install vcpkg and the lib:
git clone https://github.com/microsoft/vcpkg.git
cd vcpkg
bootstrap-vcpkg.bat
vcpkg install freetype:x86-windows-static
vcpkg integrate install

**Comment by myfirstevercode** [comment]
aight thanks for the reply, I will just wait and check for the guide when its available, already installed the above guide as well

**Comment by KebsCS** [comment]
I've added the guide to the readme https://github.com/KebsCS/KBotExt#development

Also new changes are now being automatically built into an .exe so download that if you just want to get the latest changes
